# Generated by Django 5.1.4 on 2024-12-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_order_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.IntegerField(default=123),
        ),
    ]
