# Generated by Django 5.1.4 on 2024-12-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_order_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
